# SITE CONFIGURATION
title: Sergios Karagiannakos # your site title
author: Sergios Karagiannakos # You :P
description:  Machine Learning Engineer,Software Engineer,Data Scientist # Meta description of Homepagez
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sergios Karagiannakos
  links:
    - https://twitter.com/karsergios
    - https://www.facebook.com/sergios.karagiannakos
    - https://www.linkedin.com/in/sergios-karagiannakos/
    - https://github.com/SergiosKar
    - https://www.instagram.com/sergios_krg/

# THEME SETTINGS


homepage_sections:
  - {name: 'About', link: '#about'}
  - {name: 'Services', link: '#service'}
  - {name: 'Contact', link: '#contact'}

navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Portfolio', link: '/portfolio'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Contact', link: '/contact'}



tagline: >
  Machine Learning Engineer,Software Engineer,Data Scientist 

hero_img: background_img2.jpg 

email: sergioskarag@gmail.com # email for form submission

twitter_username: karsergios # replace with your_twitter_username or comment to remove link from footer
github_username:  SergiosKar # replace with your_github_username or comment to remove link from footer
instagram_username: sergios_krg # replace with your_instagram_username or comment to remove link from footer
facebook_username: sergios.karagiannakos
linkedin_username: sergios-karagiannakos

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-WMXQPRS # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  
include: ['_pages']
permalink: /:title/

collections:
  projects:
    output: true
    permalink: /portfolio/:path/

# paginate: 6
# paginate_path: 'page:num/'

# pagination:
#      enabled: true
#      per_page: 3
#      title: ':title - page :num'
#      limit: 0
#      trail: 
#         before: 2
#         after: 2

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
 # - jekyll-paginate

# Build settings
sass:
  sass_dir: css
