# SITE CONFIGURATION
title: Sergios Karagiannakos # your site title
author: Sergios Karagiannakos # You :P
description: Sergios Karagiannakos personal blog # Meta description of Homepagez
  Sergios Karagiannakos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sergioskar.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sergios Karagiannakos
  links:
    - https://twitter.com/karsergios
    - https://www.facebook.com/sergios.karagiannakos
    - https://www.linkedin.com/in/sergios-karagiannakos/
    - https://github.com/SergiosKar
    - https://www.instagram.com/sergios_krg/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Hi! I am Sergios and I am a Machine Learning Engineer/Data Scientist. Lets chat.
  
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: sergioskarag@gmail.com # email for form submission

twitter_username: karsergios # replace with your_twitter_username or comment to remove link from footer
github_username:  SergiosKar # replace with your_github_username or comment to remove link from footer
instagram_username: sergios_krg # replace with your_instagram_username or comment to remove link from footer
facebook_username: sergios.karagiannakos
linkedin_username: sergios-karagiannakos

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
